# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import scanemails_pb2 as scanemails__pb2


class ScanEmailsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetScanEmailsData = channel.unary_stream(
        '/ScanEmails/GetScanEmailsData',
        request_serializer=scanemails__pb2.ScanEmailsQuery.SerializeToString,
        response_deserializer=scanemails__pb2.ScanEmailsResponse.FromString,
        )


class ScanEmailsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetScanEmailsData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ScanEmailsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetScanEmailsData': grpc.unary_stream_rpc_method_handler(
          servicer.GetScanEmailsData,
          request_deserializer=scanemails__pb2.ScanEmailsQuery.FromString,
          response_serializer=scanemails__pb2.ScanEmailsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ScanEmails', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
